-- CreateTable
CREATE TABLE "Settings" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT DEFAULT 1,
    "totalSalary" INTEGER NOT NULL DEFAULT 32000,
    "rent" INTEGER NOT NULL DEFAULT 8500,
    "savingsTarget" INTEGER NOT NULL DEFAULT 6200,
    "fixedCost" INTEGER NOT NULL DEFAULT 3000
);

-- CreateTable
CREATE TABLE "Expense" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "amount" INTEGER NOT NULL,
    "name" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
